#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class StackPanel;
                ref class TextBlock;
                ref class ComboBox;
                ref class TextBox;
                ref class ToggleSwitch;
                ref class Slider;
                ref class Button;
                ref class SwapChainPanel;
                ref class ProgressBar;
                ref class Border;
                ref class Image;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                ref class TranslateTransform;
            }
        }
    }
}

namespace Harness
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Media::TranslateTransform^ NavBarShift;
        private: ::Windows::UI::Xaml::Controls::Grid^ OobePanel;
        private: ::Windows::UI::Xaml::Controls::Grid^ ActionMenu;
        private: ::Windows::UI::Xaml::Controls::Grid^ Drawer;
        private: ::Windows::UI::Xaml::Controls::Grid^ SettingsPage;
        private: ::Windows::UI::Xaml::Controls::Grid^ TabSwitcher;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ TabList;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TabSwitcherTitle;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SetLangCombo;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SetSearchCombo;
        private: ::Windows::UI::Xaml::Controls::TextBox^ SetHomeBox;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetUaSwitch;
        private: ::Windows::UI::Xaml::Controls::TextBox^ SetUaCustomBox;
        private: ::Windows::UI::Xaml::Controls::Slider^ SetZoomSlider;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetGpuSwitch;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetJitSwitch;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SetClarityCombo;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetPerfLogSwitch;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetUpdateSwitch;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SetPrefetchCombo;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ SetPageWidthCombo;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetScrollFabSwitch;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetAxisLockSwitch;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetDtapZoomSwitch;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetHideNavBarSwitch;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ SetHideStatusBarSwitch;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ VersionText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ AboutFooterText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ SetZoomLabel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ DrawerList;
        private: ::Windows::UI::Xaml::Controls::Button^ TabFav;
        private: ::Windows::UI::Xaml::Controls::Button^ TabHist;
        private: ::Windows::UI::Xaml::Controls::Button^ TabDl;
        private: ::Windows::UI::Xaml::Controls::Button^ ActionBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ GpuBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ UaBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ActUaLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ BackBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ FwdBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ActFavLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ TabsBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ MenuBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LockIcon;
        private: ::Windows::UI::Xaml::Controls::TextBox^ UrlBox;
        private: ::Windows::UI::Xaml::Controls::Button^ UrlActionBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ UrlActionGlyph;
        private: ::Windows::UI::Xaml::Controls::Button^ UrlClearBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TabCountText;
        private: ::Windows::UI::Xaml::Controls::Border^ ContentBorder;
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ GpuPanel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ ImeBox;
        private: ::Windows::UI::Xaml::Controls::Border^ TitleRow;
        private: ::Windows::UI::Xaml::Media::TranslateTransform^ TitleRowShift;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TitleText;
        private: ::Windows::UI::Xaml::Controls::Border^ ProgressStrip;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ Progress;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ScrollFab;
        private: ::Windows::UI::Xaml::Controls::Border^ FindBar;
        private: ::Windows::UI::Xaml::Controls::Border^ SuggestPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ SuggestList;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ FindCount;
        private: ::Windows::UI::Xaml::Controls::Button^ FindPrev;
        private: ::Windows::UI::Xaml::Controls::Button^ FindNext;
        private: ::Windows::UI::Xaml::Controls::Button^ FindClose;
        private: ::Windows::UI::Xaml::Controls::TextBox^ FindBox;
        private: ::Windows::UI::Xaml::Controls::Grid^ ContentArea;
        private: ::Windows::UI::Xaml::Controls::Image^ RenderImage;
        private: ::Windows::UI::Xaml::Controls::Grid^ LinkMenu;
        private: ::Windows::UI::Xaml::Controls::Border^ LinkMenuCard;
        private: ::Windows::UI::Xaml::Controls::Button^ LinkMenuOpenBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LinkMenuOpenLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ LinkMenuTarget;
        // Apotheosis (0.2.5.15): 长按菜单的复制/全选/分享行(与 LinkMenuOpenBtn 同一张卡)。
        private: ::Windows::UI::Xaml::Controls::Button^ CtxCopyLinkBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CtxCopyLinkLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ CtxCopyBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CtxCopyLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ CtxSelectAllBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CtxSelectAllLabel;
        private: ::Windows::UI::Xaml::Controls::Button^ CtxShareBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ CtxShareLabel;
        // Apotheosis (0.2.5.15): <select> 下拉弹窗(UIRequestSelect)。
        private: ::Windows::UI::Xaml::Controls::Grid^ SelectPopup;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ SelectPopupTitle;
        private: ::Windows::UI::Xaml::Controls::ListView^ SelectPopupList;
        // Apotheosis (0.2.5.16): <input type=color> / <input type=date/time> choosers。
        private: ::Windows::UI::Xaml::Controls::Grid^ ColorChooser;
        private: ::Windows::UI::Xaml::Controls::Border^ ColorChooserPreview;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ColorChooserLabel;
        private: ::Windows::UI::Xaml::Controls::Grid^ ColorChooserGrid;
        private: ::Windows::UI::Xaml::Controls::Button^ ColorChooserOkBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ ColorChooserCancelBtn;
        private: ::Windows::UI::Xaml::Controls::Grid^ DateTimeChooser;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ DateTimeChooserLabel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ DateTimeDateLabel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ DateTimeDateBox;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ DateTimeTimeLabel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ DateTimeTimeBox;
        private: ::Windows::UI::Xaml::Controls::Button^ DateTimeChooserOkBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ DateTimeChooserCancelBtn;
        // Apotheosis (2026-09-27): window.prompt() 自绘输入框(MessageDialog 无输入能力)。
        private: ::Windows::UI::Xaml::Controls::Grid^ PromptBox;
        private: ::Windows::UI::Xaml::Controls::Border^ PromptBoxCard;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ PromptBoxMessage;
        private: ::Windows::UI::Xaml::Controls::TextBox^ PromptBoxInput;
        private: ::Windows::UI::Xaml::Controls::Button^ PromptBoxOkBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ PromptBoxCancelBtn;
    };
}

